# Generated by Django 4.0.6 on 2022-07-26 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CltDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltId', models.PositiveIntegerField(null=True)),
                ('cltName', models.CharField(max_length=40)),
                ('ProAssignedName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proId', models.PositiveIntegerField(null=True)),
                ('cltId', models.PositiveIntegerField(null=True)),
                ('proName', models.CharField(max_length=40, null=True)),
                ('cltName', models.CharField(max_length=40, null=True)),
                ('rdvDate', models.DateTimeField(auto_now=True)),
                ('comm', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name': 'Professionel'},
        ),
        migrations.RemoveField(
            model_name='pro',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='pro',
            name='cond',
            field=models.BooleanField(default=False, verbose_name='Conditions'),
        ),
        migrations.AddField(
            model_name='pro',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/docteurs/'),
        ),
        migrations.AddField(
            model_name='pro',
            name='spec',
            field=models.CharField(choices=[('Generaliste', 'Generaliste'), ('Cardiologue', 'Cardiologue'), ('Dermatologue', 'Dermatologue'), ('Spécialiste en médecine durgence', 'Spécialiste en médecine durgence'), ('Allergologues/Immunologues', 'Allergologues/Immunologues'), ('Anesthésistes', 'Anesthésistes'), ('Chirurgiens du côlon et du rectum', 'Chirurgiens du côlon et du rectum')], default='Generaliste', max_length=50),
        ),
        migrations.AddField(
            model_name='pro',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pro'),
        ),
        migrations.CreateModel(
            name='Clt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/patients/')),
                ('contact', models.CharField(max_length=10)),
                ('admitDate', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=100)),
                ('proAssignId', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='clt')),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
    ]
